### ISSUE TITLE
Newer version of DBUtils has different naming schema

### ISSUE THREAD

**Issue by cdudarchiktw** [braedon/prometheus-mysql-exporter#16]
It seems that newer versions of DBUtils (and will automatically install if using pip3 to install this exporter) have a slightly different naming schema. Instead of DBUtils and PersistentDB, it was changed to dbutils and persistent_db. Thus, the exporter will have issues running unless the import statement is changed to:
`from dbutils.persistent_db import PersistentDB`

Unrelated, but it doesn't appear the exporter has a way to input mysql passwords via a secure prompt, and can only be done as an argument. This is generally a poor security practice. A quick fix is to add
`from getpass import getpass`
comment out the two lines at line ~160 that starts with
`@click.option('--mysql password...`
and change line ~191 to
`password = getpass()`

This does make it so that the program asks for the password every time, but it fit our needs and you can likely just hit enter if no password is necessary.

**Comment by braedon** [comment]
Hi @cdudarchiktw, thanks for reporting the DBUtils issue. I'll release a patch with a DBUtils 1.x version restriction, and upgrade to 2.x in the next minor release.

Regarding the password, the exporter is generally run by some sort of deployment system that has its own way of managing password security, rather than run manually on an interactive command line. e.g. in Kubernetes, you can store the password in a secret, and map it to the `MYSQL_EXPORTER_MYSQL_PASSWORD` environment variable in the exporter pod. There's usually no reasonable way to provide a password interactively.

However, if you have a use case for running it interactively, please open a separate issue, and I can look into adding an additional interactive password input option.

**Comment by braedon** [comment]
Fixed in [0.4.2](https://github.com/braedon/prometheus-mysql-exporter/releases/tag/0.4.2)
